/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.ListIterator;
import java.util.Optional;
import java.util.Scanner;

public class Work {

    private ArrayList<GoodWordEntry> goodWordEntryList = new ArrayList<GoodWordEntry>();
    private int id = 1;

    enum Command {
        시작, 등록, 목록, 삭제, 수정, 빌드, 종료;

        static Command parse(String str) {
            // 아 모르겠다. 걍 해.
            try {
                return Command.valueOf(str);
            } catch (IllegalArgumentException e) {
                return Command.종료;
            } catch (Exception e) {
                System.err.println(e);
                return Command.종료;
            }
        }
    }

    Command getCommand() {
        System.out.print("명령) ");
        Scanner sc = new Scanner(System.console().reader());

        Command command = Command.parse(sc.next());
        sc.close();

        return command;
    }

    void register() {
        System.out.print("명언 : ");
        Scanner sc1 = new Scanner(System.console().reader());
        String goodword = sc1.nextLine();

        System.out.print("작가 : ");
        Scanner sc2 = new Scanner(System.console().reader());
        String writer = sc2.nextLine();

        GoodWordEntry entry = new GoodWordEntry(id, writer, goodword);

        goodWordEntryList.add(entry);

        GoodWordFileWriter.writeJson(entry);
        GoodWordFileWriter.writeListId(id);
        System.out.println(id + "번 명언이 등록되었습니다");

        id++;

        sc1.close();
        sc2.close();
    }

    void list() {
        System.out.println("번호 / 작가 / 명언");
        System.out.println("----------------------");

        ListIterator<GoodWordEntry> ite = goodWordEntryList.listIterator(goodWordEntryList.size());
        while (ite.hasPrevious()) {
            GoodWordEntry entry = ite.previous();
            int sequence = entry.getId();
            String writer = entry.getWriter();
            String goodWord = entry.getGoodword();

            System.out.println(sequence + " / " + writer + " / " + goodWord);
        }
    }

    void modify() {
        System.out.print("수정?id=");
        Scanner sc1 = new Scanner(System.console().reader());
        int sequence = sc1.nextInt();

        Optional<GoodWordEntry> optionalEntry = goodWordEntryList.stream().filter(g -> g.getId() == sequence)
                .findFirst();

        if (optionalEntry.isPresent()) {
            GoodWordEntry goodWordEntry = optionalEntry.get();

            System.out.println("명언(기존) : " + goodWordEntry.getGoodword());
            System.out.print("명언 : ");

            Scanner sc2 = new Scanner(System.console().reader());

            goodWordEntry.setGoodword(sc2.nextLine());

            System.out.println("작가(기존) : " + goodWordEntry.getGoodword());
            System.out.print("작가: ");

            Scanner sc3 = new Scanner(System.console().reader());

            goodWordEntry.setWriter(sc3.nextLine());

            GoodWordFileWriter.writeJson(goodWordEntry);

            sc2.close();
            sc3.close();

        } else {
            System.out.println(sequence + "번 명언은 존재하지 않습니다.");
        }

        sc1.close();
    }

    void delete() {
        System.out.print("삭제?id=");
        Scanner sc = new Scanner(System.console().reader());
        int sequence = sc.nextInt();

        boolean result = goodWordEntryList.removeIf(g -> g.getId() == sequence);

        if (result == true) {
            System.out.println(sequence + "번 명언이 삭제되었습니다.");
        } else {
            System.out.println(sequence + "번 명언은 존재하지 않습니다.");
        }

        sc.close();
    }

    void build() {
        GoodWordFileWriter.writeData(goodWordEntryList);
        System.out.println("data.json 파일의 내용이 갱신되었습니다.");
    }

    void quit() {
        System.out.print("명령) 종료");
    }

    // 테스트가 너무 어렵다. 어떡하지?
    void run() {

        System.out.println("== 명언 앱 ==");

        Command command = Command.시작;
        while (command.equals(Command.종료) == false) {
            command = getCommand();

            switch (command) {
                case Command.등록:
                    register();
                    break;
                case Command.목록:
                    list();
                    break;
                case Command.삭제:
                    delete();
                    break;
                case Command.수정:
                    modify();
                    break;
                case Command.빌드:
                    // TODO
                    break;
                case Command.종료:
                default:
                    quit();
                    break;
            }
        }

    }

    public static void main(String[] args) {
        new Work().run();
    }
}
