/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;

class AppTest {

    Work work = new Work();

    @Test
    void registerTest() {
        work.register();
    }

    @Test
    void listTest() {
        work.list();
    }

    @Test
    void getJsonTest() {
        JsonBuilder.add("string", "str");
        JsonBuilder.add("integer", 1);

        System.out.println(JsonBuilder.getJson());
    }

    @Test
    void pathApiExample() throws IOException {
        boolean precondition = Files.exists(Path.of("./db/wiseSaying"));

        assertEquals(false, precondition);
        Files.createDirectories(Path.of("./db/wiseSaying"));

        boolean postcondition = Files.exists(Path.of("./db/wiseSaying"));

        assertEquals(true, postcondition);

    }
}
